#!/bin/bash

# Hook for custom builds required from hub.docker.com

# ENV VARs are set by the cloud.docker.com build process,
# and are available during automated builds, automated tests,
# and while executing hooks.
# https://docs.docker.com/docker-hub/builds/advanced/
docker build -t $IMAGE_NAME .
exit
