#!/bin/bash

# This build hook is required to be able to pass environment variables
# declared in the Docker Hub build process to the Dockerfile
# that builds the image.
# https://docs.docker.com/docker-hub/builds/advanced/

docker build -t $IMAGE_NAME --build-arg UNSPLASH_APP_NAME=$UNSPLASH_APP_NAME --build-arg UNSPLASH_APP_ACCESS_KEY=$UNSPLASH_APP_ACCESS_KEY --build-arg UNSPLASH_APP_SECRET_KEY=$UNSPLASH_APP_SECRET_KEY .
exit
